services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  web:
    build:
      context: ./Evidence Protector Web UI
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"
